central_first_homepage:
    path:     /index
    defaults: { _controller: centralFirstBundle:Default:index }

central_first_test:
    path:     /test/{var}
    defaults: { _controller: centralFirstBundle:Default:test }

central_todo_list:
    path:     /todo/list
    defaults: { _controller: centralFirstBundle:ToDo:index }

central_todo_add:
    path:     /todo/add/{cle}/{valeur}
    defaults: { _controller: centralFirstBundle:ToDo:add }

central_todo_update:
    path:     /todo/update/{cle}/{valeur}
    defaults: { _controller: centralFirstBundle:ToDo:update }

central_todo_delete:
    path:     /todo/delete/{cle}
    defaults: { _controller: centralFirstBundle:ToDo:delete }

central_personne_list:
    path:     /personne/list
    defaults: { _controller: centralFirstBundle:Personne:index }

central_personne_add:
    path:     /personne/add/{prenom}/{nom}/{age}
    defaults: { _controller: centralFirstBundle:Personne:add }
    requirements:
        age: \d{2}

central_personne_one:
    path:     /personne/info/{personne}
    defaults: { _controller: centralFirstBundle:Personne:onePersonne }

central_personne_update:
    path:     /personne/update/{personne}/{prenom}/{nom}/{age}
    defaults: { _controller: centralFirstBundle:Personne:updatePersonne }

central_personne_delete:
    path:     /personne/delete/{personne}
    defaults: { _controller: centralFirstBundle:Personne:deletePersonne }

add_etudiant:
    path: /etudiant/add
    defaults: {_controller: centralFirstBundle:Etudiant:add}